import { randomUUID } from "node:crypto";
import type { AssetStore } from "./assets.js";
import type { SqliteDatabase } from "./db/index.js";
import { AppError } from "./errors.js";
import type { AssetDto, Capability, ConversationDto, JobDto, MessageDto, ModelDto, Operation, ProfileDto, ProviderId, RunDto, RunStatus } from "../shared/contracts.js";

const now = () => new Date().toISOString();
const parse = <T>(value: string | null | undefined, fallback: T): T => { try { return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } };
const supportedCapabilities = new Set<Capability>(["imageGenerate", "videoGenerate"]);
const normalizeCapabilities = (value: unknown): Capability[] => Array.isArray(value) ? value.filter((capability): capability is Capability => typeof capability === "string" && supportedCapabilities.has(capability as Capability)) : [];
type ProfileRow = { id: string; name: string; plugin_id: ProviderId; base_url: string; config_json: string; key_encrypted: string; enabled: number; last_test_json: string | null; created_at: string; updated_at: string };
type ModelRow = { id: string; profile_id: string; provider_model_id: string; label: string; capabilities_json: string; manual: number; enabled: number; created_at: string; updated_at: string };
type RunRow = { id: string; profile_id: string; model_id: string; operation: Operation; status: RunStatus; input_json: string; output_json: string | null; inspector_json: string | null; error_json: string | null; conversation_id: string | null; created_at: string; updated_at: string };
type ConversationRow = { id: string; profile_id: string; model_id: string; title: string; created_at: string; updated_at: string };
type JobRow = { id: string; run_id: string; state: string; remote_id: string | null; attempts: number; next_poll_at: string | null; created_at: string; updated_at: string };
type AssetRow = { id: string; mime_type: string; byte_size: number; storage_key: string; created_at: string };

export class Repository {
  constructor(private readonly sqlite: SqliteDatabase, private readonly assetStore: AssetStore) {}
  profileDto(row: ProfileRow): ProfileDto { return { id: row.id, name: row.name, pluginId: row.plugin_id, baseUrl: row.base_url, config: parse(row.config_json, {}), enabled: Boolean(row.enabled), hasKey: Boolean(row.key_encrypted), lastTest: parse(row.last_test_json, null), createdAt: row.created_at, updatedAt: row.updated_at }; }
  modelDto(row: ModelRow): ModelDto { return { id: row.id, profileId: row.profile_id, providerModelId: row.provider_model_id, label: row.label, capabilities: normalizeCapabilities(parse<unknown>(row.capabilities_json, [])), operationConfigs: {}, adapted: true, manual: Boolean(row.manual), enabled: Boolean(row.enabled), createdAt: row.created_at }; }
  runDto(row: RunRow): RunDto { return { id: row.id, profileId: row.profile_id, modelId: row.model_id, operation: row.operation, status: row.status, input: parse(row.input_json, {}), output: parse(row.output_json, null), assets: this.assetsForRun(row.id), inspector: parse(row.inspector_json, null), error: parse(row.error_json, null), createdAt: row.created_at, updatedAt: row.updated_at }; }
  jobDto(row: JobRow): JobDto { return { id: row.id, runId: row.run_id, state: row.state, remoteId: row.remote_id, attempts: row.attempts, nextPollAt: row.next_poll_at, createdAt: row.created_at, updatedAt: row.updated_at }; }
  private assetDto(row: AssetRow): AssetDto { return { id: row.id, mimeType: row.mime_type, byteSize: row.byte_size, url: `/api/assets/${row.id}`, createdAt: row.created_at }; }
  assetsForRun(runId: string) { return (this.sqlite.prepare("SELECT a.* FROM assets a JOIN run_assets ra ON ra.asset_id=a.id WHERE ra.run_id=? ORDER BY a.created_at").all(runId) as AssetRow[]).map((row) => this.assetDto(row)); }

  listProfiles() { return (this.sqlite.prepare("SELECT * FROM profiles ORDER BY updated_at DESC").all() as ProfileRow[]).map((row) => this.profileDto(row)); }
  getProfileRaw(id: string) { const row = this.sqlite.prepare("SELECT * FROM profiles WHERE id=?").get(id) as ProfileRow | undefined; if (!row) throw new AppError("PROFILE_NOT_FOUND", "Connection not found", 404); return row; }
  getProfile(id: string) { return this.profileDto(this.getProfileRaw(id)); }
  createProfile(input: { id: string; name: string; pluginId: ProviderId; baseUrl: string; config: Record<string, unknown>; keyEncrypted: string }) { const time = now(); this.sqlite.prepare("INSERT INTO profiles (id,name,plugin_id,base_url,config_json,key_encrypted,enabled,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)").run(input.id, input.name, input.pluginId, input.baseUrl, JSON.stringify(input.config), input.keyEncrypted, 1, time, time); return this.getProfile(input.id); }
  updateProfile(id: string, input: { name: string; baseUrl: string; config: Record<string, unknown>; enabled: boolean; keyEncrypted?: string }) { this.getProfileRaw(id); const time = now(); this.sqlite.prepare("UPDATE profiles SET name=?,base_url=?,config_json=?,enabled=?,key_encrypted=COALESCE(?,key_encrypted),updated_at=? WHERE id=?").run(input.name, input.baseUrl, JSON.stringify(input.config), Number(input.enabled), input.keyEncrypted ?? null, time, id); return this.getProfile(id); }
  deleteProfile(id: string) { this.getProfileRaw(id); this.sqlite.transaction(() => { this.sqlite.prepare("DELETE FROM models WHERE profile_id=?").run(id); this.sqlite.prepare("DELETE FROM profiles WHERE id=?").run(id); })(); }
  setProfileTest(id: string, result: { ok: boolean; at: string; detail?: string }) { this.sqlite.prepare("UPDATE profiles SET last_test_json=?,updated_at=? WHERE id=?").run(JSON.stringify(result), now(), id); return this.getProfile(id); }

  listModels(profileId: string) { this.getProfileRaw(profileId); return (this.sqlite.prepare("SELECT * FROM models WHERE profile_id=? ORDER BY manual DESC,label COLLATE NOCASE").all(profileId) as ModelRow[]).map((row) => this.modelDto(row)); }
  getModel(id: string) { const row = this.sqlite.prepare("SELECT * FROM models WHERE id=?").get(id) as ModelRow | undefined; if (!row) throw new AppError("MODEL_NOT_FOUND", "Model not found", 404); return this.modelDto(row); }
  getModelForProfile(profileId: string, modelId: string) { const model = this.getModel(modelId); if (model.profileId !== profileId) throw new AppError("MODEL_PROFILE_MISMATCH", "Model does not belong to this connection", 400); return model; }
  upsertModel(input: { profileId: string; providerModelId: string; label?: string; capabilities: Capability[]; manual: boolean; enabled?: boolean }) { const existing = this.sqlite.prepare("SELECT id FROM models WHERE profile_id=? AND provider_model_id=?").get(input.profileId, input.providerModelId) as { id: string } | undefined; const time = now(); if (existing) { this.sqlite.prepare("UPDATE models SET label=?,capabilities_json=?,manual=?,enabled=?,updated_at=? WHERE id=?").run(input.label ?? input.providerModelId, JSON.stringify(input.capabilities), Number(input.manual), Number(input.enabled ?? true), time, existing.id); return this.getModel(existing.id); } const id = randomUUID(); this.sqlite.prepare("INSERT INTO models (id,profile_id,provider_model_id,label,capabilities_json,manual,enabled,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)").run(id, input.profileId, input.providerModelId, input.label ?? input.providerModelId, JSON.stringify(input.capabilities), Number(input.manual), Number(input.enabled ?? true), time, time); return this.getModel(id); }
  replaceDiscoveredModels(profileId: string, discovered: { providerModelId: string; label?: string; capabilities: Capability[] }[]) { this.getProfileRaw(profileId); this.sqlite.transaction(() => { this.sqlite.prepare("DELETE FROM models WHERE profile_id=? AND manual=0").run(profileId); for (const model of discovered) { const capabilities = normalizeCapabilities(model.capabilities); this.upsertModel({ ...model, capabilities, profileId, manual: false }); } })(); return this.listModels(profileId); }
  deleteModel(id: string) { this.getModel(id); this.sqlite.prepare("DELETE FROM models WHERE id=?").run(id); }

  createConversation(profileId: string, modelId: string, title = "New conversation") { this.getModelForProfile(profileId, modelId); const id = randomUUID(); const time = now(); this.sqlite.prepare("INSERT INTO conversations (id,profile_id,model_id,title,created_at,updated_at) VALUES (?,?,?,?,?,?)").run(id, profileId, modelId, title, time, time); return this.getConversation(id); }
  getConversation(id: string) { const row = this.sqlite.prepare("SELECT * FROM conversations WHERE id=?").get(id) as ConversationRow | undefined; if (!row) throw new AppError("CONVERSATION_NOT_FOUND", "Conversation not found", 404); const messages = (this.sqlite.prepare("SELECT * FROM messages WHERE conversation_id=? ORDER BY created_at").all(id) as { id: string; role: "system" | "user" | "assistant"; content: string; asset_ids_json: string; created_at: string }[]).map((message): MessageDto => ({ id: message.id, role: message.role, content: message.content, assets: parse<string[]>(message.asset_ids_json, []).map((assetId) => this.assetDto(this.assetStore.find(assetId) as AssetRow)), createdAt: message.created_at })); return { id: row.id, profileId: row.profile_id, modelId: row.model_id, title: row.title, createdAt: row.created_at, updatedAt: row.updated_at, messages } satisfies ConversationDto; }
  listConversations() { return (this.sqlite.prepare("SELECT * FROM conversations ORDER BY updated_at DESC").all() as ConversationRow[]).map((row): ConversationDto => ({ id: row.id, profileId: row.profile_id, modelId: row.model_id, title: row.title, createdAt: row.created_at, updatedAt: row.updated_at })); }
  addMessage(conversationId: string, role: "system" | "user" | "assistant", content: string, assetIds: string[] = []) { this.getConversation(conversationId); const id = randomUUID(); const time = now(); this.sqlite.prepare("INSERT INTO messages (id,conversation_id,role,content,asset_ids_json,created_at) VALUES (?,?,?,?,?,?)").run(id, conversationId, role, content, JSON.stringify(assetIds), time); this.sqlite.prepare("UPDATE conversations SET title=CASE WHEN title='New conversation' AND ?='user' THEN substr(?,1,80) ELSE title END,updated_at=? WHERE id=?").run(role, content, time, conversationId); return id; }
  deleteConversation(id: string) { this.getConversation(id); this.sqlite.transaction(() => { this.sqlite.prepare("DELETE FROM messages WHERE conversation_id=?").run(id); this.sqlite.prepare("DELETE FROM conversations WHERE id=?").run(id); })(); }

  createRun(input: { profileId: string; modelId: string; operation: Operation; status: RunStatus; input: Record<string, unknown>; conversationId?: string }) { this.getModelForProfile(input.profileId, input.modelId); const id = randomUUID(); const time = now(); this.sqlite.prepare("INSERT INTO runs (id,profile_id,model_id,operation,status,input_json,conversation_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)").run(id, input.profileId, input.modelId, input.operation, input.status, JSON.stringify(input.input), input.conversationId ?? null, time, time); return this.getRun(id); }
  getRun(id: string) { const row = this.sqlite.prepare("SELECT * FROM runs WHERE id=?").get(id) as RunRow | undefined; if (!row) throw new AppError("RUN_NOT_FOUND", "Run not found", 404); return this.runDto(row); }
  listRuns() { return (this.sqlite.prepare("SELECT * FROM runs ORDER BY created_at DESC LIMIT 300").all() as RunRow[]).map((row) => this.runDto(row)); }
  finishRun(id: string, status: Extract<RunStatus, "success" | "error" | "cancelled" | "uncertain">, output: Record<string, unknown> | null, inspector: Record<string, unknown> | null, error?: { code: string; message: string }) { const current = this.getRun(id); if (["success", "error", "cancelled", "uncertain"].includes(current.status)) return current; this.sqlite.prepare("UPDATE runs SET status=?,output_json=?,inspector_json=?,error_json=?,updated_at=? WHERE id=?").run(status, output ? JSON.stringify(output) : null, inspector ? JSON.stringify(inspector) : null, error ? JSON.stringify(error) : null, now(), id); return this.getRun(id); }
  setRunInspector(id: string, inspector: Record<string, unknown>) { this.sqlite.prepare("UPDATE runs SET inspector_json=?,updated_at=? WHERE id=?").run(JSON.stringify(inspector), now(), id); }
  linkAssets(runId: string, assets: AssetDto[], kind = "result") { const statement = this.sqlite.prepare("INSERT OR IGNORE INTO run_assets (run_id,asset_id,kind) VALUES (?,?,?)"); const tx = this.sqlite.transaction(() => assets.forEach((asset) => statement.run(runId, asset.id, kind))); tx(); }
  deleteRun(id: string) { this.getRun(id); this.sqlite.transaction(() => { this.sqlite.prepare("DELETE FROM run_assets WHERE run_id=?").run(id); this.sqlite.prepare("DELETE FROM jobs WHERE run_id=?").run(id); this.sqlite.prepare("DELETE FROM runs WHERE id=?").run(id); })(); }

  createJob(runId: string) { const id = randomUUID(); const time = now(); this.sqlite.prepare("INSERT INTO jobs (id,run_id,state,attempts,created_at,updated_at) VALUES (?,?,?,?,?,?)").run(id, runId, "queued", 0, time, time); return this.getJobForRun(runId); }
  getJobForRun(runId: string) { const row = this.sqlite.prepare("SELECT * FROM jobs WHERE run_id=?").get(runId) as JobRow | undefined; if (!row) throw new AppError("JOB_NOT_FOUND", "Async job not found", 404); return this.jobDto(row); }
  getJobRawForRun(runId: string) { const row = this.sqlite.prepare("SELECT * FROM jobs WHERE run_id=?").get(runId) as JobRow | undefined; if (!row) throw new AppError("JOB_NOT_FOUND", "Async job not found", 404); return row; }
  dueJobs() { const time = now(); return this.sqlite.prepare("SELECT * FROM jobs WHERE (state='queued' OR (state='polling' AND (next_poll_at IS NULL OR next_poll_at<=?))) ORDER BY updated_at LIMIT 8").all(time) as JobRow[]; }
  markSubmitting(id: string) { this.sqlite.prepare("UPDATE jobs SET state='submitting',attempts=attempts+1,updated_at=? WHERE id=? AND state='queued'").run(now(), id); }
  markPolling(id: string, remoteId: string) { const time = now(); this.sqlite.prepare("UPDATE jobs SET state='polling',remote_id=?,next_poll_at=?,updated_at=? WHERE id=?").run(remoteId, new Date(Date.now() + 5_000).toISOString(), time, id); }
  markJobDone(id: string, state: "success" | "error" | "cancelled" | "uncertain") { this.sqlite.prepare("UPDATE jobs SET state=?,next_poll_at=NULL,updated_at=? WHERE id=?").run(state, now(), id); }
  cancelJob(runId: string) { this.sqlite.prepare("UPDATE jobs SET state='cancelled',updated_at=? WHERE run_id=? AND state NOT IN ('success','error','uncertain')").run(now(), runId); }
  clearHistory() { this.sqlite.transaction(() => { this.sqlite.exec("DELETE FROM messages; DELETE FROM conversations; DELETE FROM run_assets; DELETE FROM jobs; DELETE FROM runs;"); this.assetStore.clear(); })(); }
}
